# Generated by Django 4.0.1 on 2024-10-01 20:40

import django.core.validators
from django.db import migrations, models
import medicos.models


class Migration(migrations.Migration):

    dependencies = [
        ('medicos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='dia',
            field=models.DateField(help_text='Escoja una fecha del calendario', validators=[medicos.models.validar_dia]),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='horario',
            field=models.CharField(choices=[('1', '07:00 a 08:00'), ('2', '08:00 a 09:00'), ('3', '09:00 a 10:00'), ('4', '10:00 a 11:00'), ('5', '11:00 a 12:00')], max_length=10),
        ),
        migrations.AlterField(
            model_name='medico',
            name='telefone',
            field=models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator(message='formato invalido', regex='^\\+?1?\\d{9,15}$')], verbose_name='Telefono'),
        ),
    ]
