# Generated by Django 4.0.1 on 2024-10-01 20:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='cpf',
           
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='telefono',
        ),
        migrations.AddField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator(message='Formato invalido.', regex='^\\+?1?\\d{9,15}$')], verbose_name='Telefono'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='sexo',
            field=models.CharField(choices=[('MAS', 'Maculino'), ('FEM', 'Feminino')], max_length=9),
        ),
    ]
